# Fabric Properties
	# check these on https://fallen-breath.github.io/fabric-versions/?version=26.2
	minecraft_version=26.2
	parchment_version=

# Fabric Mod Metadata
	minecraft_dependency=>=26.2 <26.3
	malilib_dependency=>=0.29.3
	tweakeroo_dependency=>=0.29.2
	litematica_dependency=>=0.28.4

# Build Information
	# The target mc versions for the mod during mod publishing, separated with \n
	game_versions=26.2

# Dependencies
	fabric_api_version=0.152.1+26.2

	# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/malilib/
	malilib_version=fi.dy.masa.malilib:malilib-fabric-26.2:0.29.3

	# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/tweakeroo/
	tweakeroo_version=fi.dy.masa.tweakeroo:tweakeroo-fabric-26.2:0.29.2

	# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/litematica/
	litematica_version=fi.dy.masa.litematica:litematica-fabric-26.2:0.28.4

	# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu/
	mod_menu_version=20.0.0-beta.2
